name: Claude Test Debug

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Event
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Comment Body: ${{ github.event.comment.body }}"
        echo "Contains @claude: ${{ contains(github.event.comment.body, '@claude') }}"
        
    - name: Check Claude Mention
      if: contains(github.event.comment.body, '@claude')
      run: echo "✅ Claude mention detected!"